package com.met.auth.exception;

public enum ErrorCode {
    NOT_FOUND,
    BAD_REQUEST,
    GENERAL_ERROR,
    ILLEGAL_ARGUMENT,
    OPERATION_NOT_ALLOWED,
    CONSTRAINT_EXCEPTION,
    VALIDATION_EXCEPTION,
    PASSWORD_NOT_MATCH
}
